import faker from '@faker-js/faker';
import { FC } from 'react';
import { Helmet } from '../Helmet/Helmet.styled';
import { usePageStackRouter } from '../PageStackRouter';
import { Profile } from './Profile.styled';

interface ProfileProps {
  name: string;
}

const ProfileComponent: FC<ProfileProps> = (props) => {
  // random phone number generated by faker
  const phoneNumber = faker.phone.phoneNumber();
  const { pop } = usePageStackRouter();

  return (
    <Profile.Container>
      <Helmet.Container>
        <Helmet.Left onClick={pop}>Contacts</Helmet.Left>
        <Helmet.Title>{props.name}</Helmet.Title>
        <Helmet.Right>Edit</Helmet.Right>
      </Helmet.Container>
      <Profile.Avatar.Container>
        <Profile.Avatar.Image src={faker.image.avatar()} />
        <Profile.Avatar.Label>{props.name}</Profile.Avatar.Label>
      </Profile.Avatar.Container>
      <Profile.Phone.Container>
        <Profile.Phone.Label>Phone</Profile.Phone.Label>
        <Profile.Phone.Number>{phoneNumber}</Profile.Phone.Number>
      </Profile.Phone.Container>
      <Profile.Email.Container>
        <Profile.Email.Label>Email</Profile.Email.Label>
        <Profile.Email.Address>{faker.internet.email()}</Profile.Email.Address>
      </Profile.Email.Container>
      <Profile.Notes.Container>
        <Profile.Notes.Label>Notes</Profile.Notes.Label>
        <Profile.Notes.Text></Profile.Notes.Text>
      </Profile.Notes.Container>
    </Profile.Container>
  );
};

export { ProfileComponent };
